name: drone_workflow_env
channels:
  - defaults
dependencies:
  - python=3.12.7
  - pip=24.2
  - pip:
    - beautifulsoup4==4.12.3
    - exifread==3.0.0
    - folium==0.18.0
    - geopandas==1.0.1
    - matplotlib==3.9.3
    - pdfkit==1.0.0
    - pillow==11.0.0
    - pycountry==24.6.1
    - rasterio==1.4.3
    - requests==2.32.3
    - rpy2==3.5.12
    - xmltodict==0.14.2
    - webdriver-manager==4.0.2
    - wkhtmltopdf==0.2